### ISSUE TITLE
GPLv2 or BSD license?

### ISSUE THREAD

**Issue by xnox** [raspberrypi/libpisp#18]
```console
$ licensecheck -r . | grep -v -e BSD -e CC0 -e UNKNOWN
./.clang-format: *No copyright* GNU General Public License, Version 2
./utils/checkstyle.py: GNU General Public License, Version 2
./src/libpisp/backend/pisp_be_config.h: GNU General Public License, Version 2
./src/libpisp/common/pisp_common.h: GNU General Public License, Version 2
./src/libpisp/common/pisp_types.h: GNU General Public License, Version 2
./src/libpisp/frontend/pisp_fe_config.h: GNU General Public License, Version 2
./src/libpisp/frontend/pisp_statistics.h: GNU General Public License, Version 2
```

I'm not sure if clang-format or checkstyle.py are used.

Some header files are marked GPL v2, whilst many other files are BSD and CC0. Whilst top level project License and Readme are BSD.

Can you please double check the license declaration on the above files? As it would seem to make the whole combination to be GPLv2 and not BSD.

**Comment by naushir** [comment]
```
./src/libpisp/backend/pisp_be_config.h: GNU General Public License, Version 2
./src/libpisp/common/pisp_common.h: GNU General Public License, Version 2
./src/libpisp/common/pisp_types.h: GNU General Public License, Version 2
./src/libpisp/frontend/pisp_fe_config.h: GNU General Public License, Version 2
./src/libpisp/frontend/pisp_statistics.h: GNU General Public License, Version 2
```

These files above are pulled from the kernel headers, so the GPL header followed.  I will change these to BSD for this repo.  The checkstyle is only a git hook so is not part of the install distribution.

**Comment by 6by9** [comment]
Kernel userspace API headers (ie in include/uapi) are normally 
```/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */```

There are some licenced as
```/* SPDX-License-Identifier: ((GPL-2.0-only WITH Linux-syscall-note) OR BSD-3-Clause) */```
but those seem to be the exception.

**Comment by naushir** [comment]
Sounds like ``/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */`` is what I want then!

**Comment by xnox** [comment]
> Sounds like `/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */` is what I want then!

and then also copy that full contents of license text and note to the top level repository.

**Comment by pinchartl** [comment]
For what it's worth, I've found the reuse (https://reuse.software/) tool very useful to check for license compliance in libcamera. It can download license files for all licenses used in the project and store them in the LICENSES directory. We do so in libcamera (see our COPYING.rst), you may want to consider it for libpisp too.

**Comment by naushir** [comment]
> For what it's worth, I've found the reuse (https://reuse.software/) tool very useful to check for license compliance in libcamera. It can download license files for all licenses used in the project and store them in the LICENSES directory. We do so in libcamera (see our COPYING.rst), you may want to consider it for libpisp too.

Thanks Laurent, I'll use this tool to do similar to what libcamera does.

**Comment by naushir** [comment]
Changes have now been merged.

**Comment by xnox** [comment]
@naushir please tag 1.0.3 as at least in Ubuntu it is frowned upon / is questionable to change licensing and copyright information via a patch, as it means original tarball still has previous licensing information.
